services:

  peer-1:
    container_name: peer-1
    image: peer:latest
    ports:
      - "50052:50051"
      - "8081:8080"
      - "9091:9091"
    volumes:
      - /tmp/tp/data/peer-1:/tmp/data
      - /tmp/tp/peer-1:/tmp/peer
    environment:
      - PEER_NAME=peer-1
      - PEER_HOST=peer-1
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-1
      - METRICS_PORT=9091
      - NAME_SPACE=peer-1 
    networks:
      - tp_net

    depends_on:

      - peer-2

  peer-2:
    container_name: peer-2
    image: peer:latest
    ports:
      - "50053:50051"
      - "8082:8080"
      - "9092:9092"
    volumes:
      - /tmp/tp/data/peer-2:/tmp/data
      - /tmp/tp/peer-2:/tmp/peer
    environment:
      - PEER_NAME=peer-2
      - PEER_HOST=peer-2
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-2
      - METRICS_PORT=9092
      - NAME_SPACE=peer-2 
    networks:
      - tp_net

    depends_on:

      - peer-3

  peer-3:
    container_name: peer-3
    image: peer:latest
    ports:
      - "50054:50051"
      - "8083:8080"
      - "9093:9093"
    volumes:
      - /tmp/tp/data/peer-3:/tmp/data
      - /tmp/tp/peer-3:/tmp/peer
    environment:
      - PEER_NAME=peer-3
      - PEER_HOST=peer-3
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-3
      - METRICS_PORT=9093
      - NAME_SPACE=peer-3 
    networks:
      - tp_net

    depends_on:

      - peer-4

  peer-4:
    container_name: peer-4
    image: peer:latest
    ports:
      - "50055:50051"
      - "8084:8080"
      - "9094:9094"
    volumes:
      - /tmp/tp/data/peer-4:/tmp/data
      - /tmp/tp/peer-4:/tmp/peer
    environment:
      - PEER_NAME=peer-4
      - PEER_HOST=peer-4
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-4
      - METRICS_PORT=9094
      - NAME_SPACE=peer-4 
    networks:
      - tp_net

    depends_on:

      - peer-5

  peer-5:
    container_name: peer-5
    image: peer:latest
    ports:
      - "50056:50051"
      - "8085:8080"
      - "9095:9095"
    volumes:
      - /tmp/tp/data/peer-5:/tmp/data
      - /tmp/tp/peer-5:/tmp/peer
    environment:
      - PEER_NAME=peer-5
      - PEER_HOST=peer-5
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-5
      - METRICS_PORT=9095
      - NAME_SPACE=peer-5 
    networks:
      - tp_net

    depends_on:

      - peer-6

  peer-6:
    container_name: peer-6
    image: peer:latest
    ports:
      - "50057:50051"
      - "8086:8080"
      - "9096:9096"
    volumes:
      - /tmp/tp/data/peer-6:/tmp/data
      - /tmp/tp/peer-6:/tmp/peer
    environment:
      - PEER_NAME=peer-6
      - PEER_HOST=peer-6
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-6
      - METRICS_PORT=9096
      - NAME_SPACE=peer-6 
    networks:
      - tp_net

    depends_on:

      - peer-7

  peer-7:
    container_name: peer-7
    image: peer:latest
    ports:
      - "50058:50051"
      - "8087:8080"
      - "9097:9097"
    volumes:
      - /tmp/tp/data/peer-7:/tmp/data
      - /tmp/tp/peer-7:/tmp/peer
    environment:
      - PEER_NAME=peer-7
      - PEER_HOST=peer-7
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-7
      - METRICS_PORT=9097
      - NAME_SPACE=peer-7 
    networks:
      - tp_net

    depends_on:

      - peer-8

  peer-8:
    container_name: peer-8
    image: peer:latest
    ports:
      - "50059:50051"
      - "8088:8080"
      - "9098:9098"
    volumes:
      - /tmp/tp/data/peer-8:/tmp/data
      - /tmp/tp/peer-8:/tmp/peer
    environment:
      - PEER_NAME=peer-8
      - PEER_HOST=peer-8
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-8
      - METRICS_PORT=9098
      - NAME_SPACE=peer-8 
    networks:
      - tp_net

    depends_on:

      - peer-9

  peer-9:
    container_name: peer-9
    image: peer:latest
    ports:
      - "50060:50051"
      - "8089:8080"
      - "9099:9099"
    volumes:
      - /tmp/tp/data/peer-9:/tmp/data
      - /tmp/tp/peer-9:/tmp/peer
    environment:
      - PEER_NAME=peer-9
      - PEER_HOST=peer-9
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-9
      - METRICS_PORT=9099
      - NAME_SPACE=peer-9 
    networks:
      - tp_net

    depends_on:

      - peer-10

  peer-10:
    container_name: peer-10
    image: peer:latest
    ports:
      - "50061:50051"
      - "8090:8080"
      - "9100:9100"
    volumes:
      - /tmp/tp/data/peer-10:/tmp/data
      - /tmp/tp/peer-10:/tmp/peer
    environment:
      - PEER_NAME=peer-10
      - PEER_HOST=peer-10
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-10
      - METRICS_PORT=9100
      - NAME_SPACE=peer-10 
    networks:
      - tp_net

    depends_on:

      - peer-11

  peer-11:
    container_name: peer-11
    image: peer:latest
    ports:
      - "50062:50051"
      - "8091:8080"
      - "9101:9101"
    volumes:
      - /tmp/tp/data/peer-11:/tmp/data
      - /tmp/tp/peer-11:/tmp/peer
    environment:
      - PEER_NAME=peer-11
      - PEER_HOST=peer-11
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-11
      - METRICS_PORT=9101
      - NAME_SPACE=peer-11 
    networks:
      - tp_net

    depends_on:

      - peer-12

  peer-12:
    container_name: peer-12
    image: peer:latest
    ports:
      - "50063:50051"
      - "8092:8080"
      - "9102:9102"
    volumes:
      - /tmp/tp/data/peer-12:/tmp/data
      - /tmp/tp/peer-12:/tmp/peer
    environment:
      - PEER_NAME=peer-12
      - PEER_HOST=peer-12
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-12
      - METRICS_PORT=9102
      - NAME_SPACE=peer-12 
    networks:
      - tp_net

    depends_on:

      - peer-13

  peer-13:
    container_name: peer-13
    image: peer:latest
    ports:
      - "50064:50051"
      - "8093:8080"
      - "9103:9103"
    volumes:
      - /tmp/tp/data/peer-13:/tmp/data
      - /tmp/tp/peer-13:/tmp/peer
    environment:
      - PEER_NAME=peer-13
      - PEER_HOST=peer-13
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-13
      - METRICS_PORT=9103
      - NAME_SPACE=peer-13 
    networks:
      - tp_net

    depends_on:

      - peer-14

  peer-14:
    container_name: peer-14
    image: peer:latest
    ports:
      - "50065:50051"
      - "8094:8080"
      - "9104:9104"
    volumes:
      - /tmp/tp/data/peer-14:/tmp/data
      - /tmp/tp/peer-14:/tmp/peer
    environment:
      - PEER_NAME=peer-14
      - PEER_HOST=peer-14
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-14
      - METRICS_PORT=9104
      - NAME_SPACE=peer-14 
    networks:
      - tp_net

    depends_on:

      - peer-15

  peer-15:
    container_name: peer-15
    image: peer:latest
    ports:
      - "50066:50051"
      - "8095:8080"
      - "9105:9105"
    volumes:
      - /tmp/tp/data/peer-15:/tmp/data
      - /tmp/tp/peer-15:/tmp/peer
    environment:
      - PEER_NAME=peer-15
      - PEER_HOST=peer-15
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-15
      - METRICS_PORT=9105
      - NAME_SPACE=peer-15 
    networks:
      - tp_net

    depends_on:

      - peer-16

  peer-16:
    container_name: peer-16
    image: peer:latest
    ports:
      - "50067:50051"
      - "8096:8080"
      - "9106:9106"
    volumes:
      - /tmp/tp/data/peer-16:/tmp/data
      - /tmp/tp/peer-16:/tmp/peer
    environment:
      - PEER_NAME=peer-16
      - PEER_HOST=peer-16
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-16
      - METRICS_PORT=9106
      - NAME_SPACE=peer-16 
    networks:
      - tp_net

    depends_on:

      - peer-17

  peer-17:
    container_name: peer-17
    image: peer:latest
    ports:
      - "50068:50051"
      - "8097:8080"
      - "9107:9107"
    volumes:
      - /tmp/tp/data/peer-17:/tmp/data
      - /tmp/tp/peer-17:/tmp/peer
    environment:
      - PEER_NAME=peer-17
      - PEER_HOST=peer-17
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-17
      - METRICS_PORT=9107
      - NAME_SPACE=peer-17 
    networks:
      - tp_net

    depends_on:

      - peer-18

  peer-18:
    container_name: peer-18
    image: peer:latest
    ports:
      - "50069:50051"
      - "8098:8080"
      - "9108:9108"
    volumes:
      - /tmp/tp/data/peer-18:/tmp/data
      - /tmp/tp/peer-18:/tmp/peer
    environment:
      - PEER_NAME=peer-18
      - PEER_HOST=peer-18
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-18
      - METRICS_PORT=9108
      - NAME_SPACE=peer-18 
    networks:
      - tp_net

    depends_on:

      - peer-19

  peer-19:
    container_name: peer-19
    image: peer:latest
    ports:
      - "50070:50051"
      - "8099:8080"
      - "9109:9109"
    volumes:
      - /tmp/tp/data/peer-19:/tmp/data
      - /tmp/tp/peer-19:/tmp/peer
    environment:
      - PEER_NAME=peer-19
      - PEER_HOST=peer-19
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-19
      - METRICS_PORT=9109
      - NAME_SPACE=peer-19 
    networks:
      - tp_net

    depends_on:

      - peer-20

  peer-20:
    container_name: peer-20
    image: peer:latest
    ports:
      - "50071:50051"
      - "8100:8080"
      - "9110:9110"
    volumes:
      - /tmp/tp/data/peer-20:/tmp/data
      - /tmp/tp/peer-20:/tmp/peer
    environment:
      - PEER_NAME=peer-20
      - PEER_HOST=peer-20
      - PEER_PORT_GRPC=50051
      - PEER_PORT_TCP=8080
      - ENTRIES_PER_K_BUCKET=20
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_IPFS_FOLDER=/tmp/peer/store
      - SEARCH_WORKERS=20
      - NUMBER_OF_PAIRS=20
      - METRICS_HOST=peer-20
      - METRICS_PORT=9110
      - NAME_SPACE=peer-20 
    networks:
      - tp_net




  client-1:
    container_name: client-1
    image: client:latest
    ports:
      - "8101:8080"
      - "9111:9111"
    volumes:
      - /tmp/tp/data/client-1:/tmp/data
      - /tmp/tp/client-1:/tmp/client
    environment:
      - CLIENT_NAME=client-1
      - CLIENT_HOST=client-1
      - CLIENT_PORT=8080
      - LOGIN_FORMAT_FOR_KEYS=hex
      - INPUT_DATA_FOLDER=/tmp/data
      - STORE_FOLDER=/tmp/client/store
      - NUMBER_OF_PAIRS=20
      - NUMBER_OF_CLIENTS=1
      - METRICS_HOST=client-1
      - METRICS_PORT=9111
      - NAME_SPACE=client-1
    depends_on:
      - peer-1
    networks:
      - tp_net


  prometheus:
    image: prom/prometheus:v2.40.4
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - client-1
    networks:
      - tp_net

  metrics:
    image: metrics:latest
    container_name: metrics
    ports:
      - "9392:9392"
    depends_on:
      - prometheus
    networks:
      - tp_net
    

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./src/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana:/var/lib/grafana
    networks:
      - tp_net
 
volumes:
  grafana:

networks:
  tp_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24