services:

  peer-1:
    container_name: peer-1
    image: peer:latest
    ports:
      - "50051:50051"  # Puerto gRPC
    environment:
      - PEER_NAME=peer-1
      - PEER_HOST=peer-1
      - PEER_PORT=50051
      - ENTRIES_PER_K_BUCKET=20
    networks:
      - tp_net



networks:
  tp_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24