// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: peer.proto

package protopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Operations_Ping_FullMethodName              = "/Operations/Ping"
	Operations_ShCtsReciprocally_FullMethodName = "/Operations/ShCtsReciprocally"
	Operations_StoreBlock_FullMethodName        = "/Operations/StoreBlock"
	Operations_FindBlock_FullMethodName         = "/Operations/FindBlock"
	Operations_AddFile_FullMethodName           = "/Operations/AddFile"
)

// OperationsClient is the client API for Operations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperationsClient interface {
	// Permite hacer un ping a otro nodo enviando los datos de contacto propios
	Ping(ctx context.Context, in *PingOperands, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Permite compartir contactos recomendados entre dos pares recíprocamente
	ShCtsReciprocally(ctx context.Context, in *ShCtsRecipOpers, opts ...grpc.CallOption) (*ShCtsRecipRes, error)
	// Permite enviar un bloque a ser guardado en un nodo dado
	StoreBlock(ctx context.Context, in *StoreBlockOpers, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Permite enviar un bloque a ser guardado en un nodo dado
	FindBlock(ctx context.Context, in *FindBlockOpers, opts ...grpc.CallOption) (*FindBlockRes, error)
	// Permite subir un nodo de la red y que este último lo suba a la red
	AddFile(ctx context.Context, in *AddFileOpers, opts ...grpc.CallOption) (*AddFileRes, error)
}

type operationsClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationsClient(cc grpc.ClientConnInterface) OperationsClient {
	return &operationsClient{cc}
}

func (c *operationsClient) Ping(ctx context.Context, in *PingOperands, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Operations_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsClient) ShCtsReciprocally(ctx context.Context, in *ShCtsRecipOpers, opts ...grpc.CallOption) (*ShCtsRecipRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShCtsRecipRes)
	err := c.cc.Invoke(ctx, Operations_ShCtsReciprocally_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsClient) StoreBlock(ctx context.Context, in *StoreBlockOpers, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Operations_StoreBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsClient) FindBlock(ctx context.Context, in *FindBlockOpers, opts ...grpc.CallOption) (*FindBlockRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindBlockRes)
	err := c.cc.Invoke(ctx, Operations_FindBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsClient) AddFile(ctx context.Context, in *AddFileOpers, opts ...grpc.CallOption) (*AddFileRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFileRes)
	err := c.cc.Invoke(ctx, Operations_AddFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationsServer is the server API for Operations service.
// All implementations must embed UnimplementedOperationsServer
// for forward compatibility.
type OperationsServer interface {
	// Permite hacer un ping a otro nodo enviando los datos de contacto propios
	Ping(context.Context, *PingOperands) (*emptypb.Empty, error)
	// Permite compartir contactos recomendados entre dos pares recíprocamente
	ShCtsReciprocally(context.Context, *ShCtsRecipOpers) (*ShCtsRecipRes, error)
	// Permite enviar un bloque a ser guardado en un nodo dado
	StoreBlock(context.Context, *StoreBlockOpers) (*emptypb.Empty, error)
	// Permite enviar un bloque a ser guardado en un nodo dado
	FindBlock(context.Context, *FindBlockOpers) (*FindBlockRes, error)
	// Permite subir un nodo de la red y que este último lo suba a la red
	AddFile(context.Context, *AddFileOpers) (*AddFileRes, error)
	mustEmbedUnimplementedOperationsServer()
}

// UnimplementedOperationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationsServer struct{}

func (UnimplementedOperationsServer) Ping(context.Context, *PingOperands) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOperationsServer) ShCtsReciprocally(context.Context, *ShCtsRecipOpers) (*ShCtsRecipRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShCtsReciprocally not implemented")
}
func (UnimplementedOperationsServer) StoreBlock(context.Context, *StoreBlockOpers) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreBlock not implemented")
}
func (UnimplementedOperationsServer) FindBlock(context.Context, *FindBlockOpers) (*FindBlockRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBlock not implemented")
}
func (UnimplementedOperationsServer) AddFile(context.Context, *AddFileOpers) (*AddFileRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFile not implemented")
}
func (UnimplementedOperationsServer) mustEmbedUnimplementedOperationsServer() {}
func (UnimplementedOperationsServer) testEmbeddedByValue()                    {}

// UnsafeOperationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationsServer will
// result in compilation errors.
type UnsafeOperationsServer interface {
	mustEmbedUnimplementedOperationsServer()
}

func RegisterOperationsServer(s grpc.ServiceRegistrar, srv OperationsServer) {
	// If the following call pancis, it indicates UnimplementedOperationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Operations_ServiceDesc, srv)
}

func _Operations_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingOperands)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Operations_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).Ping(ctx, req.(*PingOperands))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operations_ShCtsReciprocally_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShCtsRecipOpers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).ShCtsReciprocally(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Operations_ShCtsReciprocally_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).ShCtsReciprocally(ctx, req.(*ShCtsRecipOpers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operations_StoreBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreBlockOpers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).StoreBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Operations_StoreBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).StoreBlock(ctx, req.(*StoreBlockOpers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operations_FindBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBlockOpers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).FindBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Operations_FindBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).FindBlock(ctx, req.(*FindBlockOpers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operations_AddFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFileOpers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).AddFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Operations_AddFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).AddFile(ctx, req.(*AddFileOpers))
	}
	return interceptor(ctx, in, info, handler)
}

// Operations_ServiceDesc is the grpc.ServiceDesc for Operations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Operations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Operations",
	HandlerType: (*OperationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Operations_Ping_Handler,
		},
		{
			MethodName: "ShCtsReciprocally",
			Handler:    _Operations_ShCtsReciprocally_Handler,
		},
		{
			MethodName: "StoreBlock",
			Handler:    _Operations_StoreBlock_Handler,
		},
		{
			MethodName: "FindBlock",
			Handler:    _Operations_FindBlock_Handler,
		},
		{
			MethodName: "AddFile",
			Handler:    _Operations_AddFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peer.proto",
}
