// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: actor.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	ProfilePath   *string                `protobuf:"bytes,2,req,name=profilePath" json:"profilePath,omitempty"`
	CountMovies   *int64                 `protobuf:"varint,3,req,name=countMovies" json:"countMovies,omitempty"`
	ClientId      *string                `protobuf:"bytes,4,req,name=clientId" json:"clientId,omitempty"`
	MessageId     *int64                 `protobuf:"varint,5,req,name=messageId" json:"messageId,omitempty"`
	SourceId      *string                `protobuf:"bytes,6,req,name=sourceId" json:"sourceId,omitempty"`
	Eof           *bool                  `protobuf:"varint,7,opt,name=eof" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{0}
}

func (x *Actor) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Actor) GetProfilePath() string {
	if x != nil && x.ProfilePath != nil {
		return *x.ProfilePath
	}
	return ""
}

func (x *Actor) GetCountMovies() int64 {
	if x != nil && x.CountMovies != nil {
		return *x.CountMovies
	}
	return 0
}

func (x *Actor) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *Actor) GetMessageId() int64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *Actor) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *Actor) GetEof() bool {
	if x != nil && x.Eof != nil {
		return *x.Eof
	}
	return false
}

var File_actor_proto protoreflect.FileDescriptor

const file_actor_proto_rawDesc = "" +
	"\n" +
	"\vactor.proto\"\xc7\x01\n" +
	"\x05Actor\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12 \n" +
	"\vprofilePath\x18\x02 \x02(\tR\vprofilePath\x12 \n" +
	"\vcountMovies\x18\x03 \x02(\x03R\vcountMovies\x12\x1a\n" +
	"\bclientId\x18\x04 \x02(\tR\bclientId\x12\x1c\n" +
	"\tmessageId\x18\x05 \x02(\x03R\tmessageId\x12\x1a\n" +
	"\bsourceId\x18\x06 \x02(\tR\bsourceId\x12\x10\n" +
	"\x03eof\x18\a \x01(\bR\x03eofB\vZ\t./protopb"

var (
	file_actor_proto_rawDescOnce sync.Once
	file_actor_proto_rawDescData []byte
)

func file_actor_proto_rawDescGZIP() []byte {
	file_actor_proto_rawDescOnce.Do(func() {
		file_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actor_proto_rawDesc), len(file_actor_proto_rawDesc)))
	})
	return file_actor_proto_rawDescData
}

var file_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_actor_proto_goTypes = []any{
	(*Actor)(nil), // 0: Actor
}
var file_actor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_actor_proto_init() }
func file_actor_proto_init() {
	if File_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actor_proto_rawDesc), len(file_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actor_proto_goTypes,
		DependencyIndexes: file_actor_proto_depIdxs,
		MessageInfos:      file_actor_proto_msgTypes,
	}.Build()
	File_actor_proto = out.File
	file_actor_proto_goTypes = nil
	file_actor_proto_depIdxs = nil
}
