// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: peer.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingOperands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      []byte                 `protobuf:"bytes,1,req,name=sourceId" json:"sourceId,omitempty"`
	SourceUrl     *string                `protobuf:"bytes,2,req,name=sourceUrl" json:"sourceUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingOperands) Reset() {
	*x = PingOperands{}
	mi := &file_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingOperands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingOperands) ProtoMessage() {}

func (x *PingOperands) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingOperands.ProtoReflect.Descriptor instead.
func (*PingOperands) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{0}
}

func (x *PingOperands) GetSourceId() []byte {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *PingOperands) GetSourceUrl() string {
	if x != nil && x.SourceUrl != nil {
		return *x.SourceUrl
	}
	return ""
}

type ShareContactsReciprocallyOperands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      []byte                 `protobuf:"bytes,1,req,name=sourceId" json:"sourceId,omitempty"`
	SourceUrl     *string                `protobuf:"bytes,2,req,name=sourceUrl" json:"sourceUrl,omitempty"`
	ContactsIds   [][]byte               `protobuf:"bytes,3,rep,name=contactsIds" json:"contactsIds,omitempty"`
	ContactsUrls  []string               `protobuf:"bytes,4,rep,name=contactsUrls" json:"contactsUrls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareContactsReciprocallyOperands) Reset() {
	*x = ShareContactsReciprocallyOperands{}
	mi := &file_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareContactsReciprocallyOperands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareContactsReciprocallyOperands) ProtoMessage() {}

func (x *ShareContactsReciprocallyOperands) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareContactsReciprocallyOperands.ProtoReflect.Descriptor instead.
func (*ShareContactsReciprocallyOperands) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{1}
}

func (x *ShareContactsReciprocallyOperands) GetSourceId() []byte {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *ShareContactsReciprocallyOperands) GetSourceUrl() string {
	if x != nil && x.SourceUrl != nil {
		return *x.SourceUrl
	}
	return ""
}

func (x *ShareContactsReciprocallyOperands) GetContactsIds() [][]byte {
	if x != nil {
		return x.ContactsIds
	}
	return nil
}

func (x *ShareContactsReciprocallyOperands) GetContactsUrls() []string {
	if x != nil {
		return x.ContactsUrls
	}
	return nil
}

type ShareContactsReciprocallyResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactsIds   [][]byte               `protobuf:"bytes,1,rep,name=contactsIds" json:"contactsIds,omitempty"`
	ContactsUrls  []string               `protobuf:"bytes,2,rep,name=contactsUrls" json:"contactsUrls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareContactsReciprocallyResults) Reset() {
	*x = ShareContactsReciprocallyResults{}
	mi := &file_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareContactsReciprocallyResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareContactsReciprocallyResults) ProtoMessage() {}

func (x *ShareContactsReciprocallyResults) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareContactsReciprocallyResults.ProtoReflect.Descriptor instead.
func (*ShareContactsReciprocallyResults) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{2}
}

func (x *ShareContactsReciprocallyResults) GetContactsIds() [][]byte {
	if x != nil {
		return x.ContactsIds
	}
	return nil
}

func (x *ShareContactsReciprocallyResults) GetContactsUrls() []string {
	if x != nil {
		return x.ContactsUrls
	}
	return nil
}

var File_peer_proto protoreflect.FileDescriptor

const file_peer_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"peer.proto\x1a\x1bgoogle/protobuf/empty.proto\"H\n" +
	"\fPingOperands\x12\x1a\n" +
	"\bsourceId\x18\x01 \x02(\fR\bsourceId\x12\x1c\n" +
	"\tsourceUrl\x18\x02 \x02(\tR\tsourceUrl\"\xa3\x01\n" +
	"!ShareContactsReciprocallyOperands\x12\x1a\n" +
	"\bsourceId\x18\x01 \x02(\fR\bsourceId\x12\x1c\n" +
	"\tsourceUrl\x18\x02 \x02(\tR\tsourceUrl\x12 \n" +
	"\vcontactsIds\x18\x03 \x03(\fR\vcontactsIds\x12\"\n" +
	"\fcontactsUrls\x18\x04 \x03(\tR\fcontactsUrls\"h\n" +
	" ShareContactsReciprocallyResults\x12 \n" +
	"\vcontactsIds\x18\x01 \x03(\fR\vcontactsIds\x12\"\n" +
	"\fcontactsUrls\x18\x02 \x03(\tR\fcontactsUrls2\x9f\x01\n" +
	"\n" +
	"Operations\x12-\n" +
	"\x04Ping\x12\r.PingOperands\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\x19ShareContactsReciprocally\x12\".ShareContactsReciprocallyOperands\x1a!.ShareContactsReciprocallyResultsB\vZ\t./protopb"

var (
	file_peer_proto_rawDescOnce sync.Once
	file_peer_proto_rawDescData []byte
)

func file_peer_proto_rawDescGZIP() []byte {
	file_peer_proto_rawDescOnce.Do(func() {
		file_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)))
	})
	return file_peer_proto_rawDescData
}

var file_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_peer_proto_goTypes = []any{
	(*PingOperands)(nil),                      // 0: PingOperands
	(*ShareContactsReciprocallyOperands)(nil), // 1: ShareContactsReciprocallyOperands
	(*ShareContactsReciprocallyResults)(nil),  // 2: ShareContactsReciprocallyResults
	(*emptypb.Empty)(nil),                     // 3: google.protobuf.Empty
}
var file_peer_proto_depIdxs = []int32{
	0, // 0: Operations.Ping:input_type -> PingOperands
	1, // 1: Operations.ShareContactsReciprocally:input_type -> ShareContactsReciprocallyOperands
	3, // 2: Operations.Ping:output_type -> google.protobuf.Empty
	2, // 3: Operations.ShareContactsReciprocally:output_type -> ShareContactsReciprocallyResults
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_peer_proto_init() }
func file_peer_proto_init() {
	if File_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peer_proto_goTypes,
		DependencyIndexes: file_peer_proto_depIdxs,
		MessageInfos:      file_peer_proto_msgTypes,
	}.Build()
	File_peer_proto = out.File
	file_peer_proto_goTypes = nil
	file_peer_proto_depIdxs = nil
}
