{
 "title": "Métricas TP",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Contact Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"peer_\\\\d+_contact_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last File Returned",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{__name__=~\"peer_\\\\d+_last_file_returned_number\"}   ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Download Time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{__name__=~\"client_\\\\d+_download_time\"}   ",
     "legendFormat": "{{fileNumber}}"
    },
    {
     "expr": "avg({__name__=~\"client_\\\\d+_download_time\"})",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}